name: Java CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Cache Gradle packages
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    #- name: Make gradlew executable
    #  run: chmod +x gradlew
    - name: Build
      run: ./gradlew bootJar
    - name: Test
      run: ./gradlew test
    - name: Publish
      run: ./gradlew -Pghtoken=${{ secrets.GITHUB_TOKEN }} --scan publish
    - name: Save Package
      uses: actions/upload-artifact@v1
      with:
        name: 1d8690130
        path: build/libs
