name: Java CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Cache Gradle packages
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: DISABLED Grant execute permission for gradlew
      run: echo chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew -Pghtoken=${{ secrets.GITHUB_TOKEN }} build
    - name: Publish with Gradle
      run: ./gradlew -Pghtoken=${{ secrets.GITHUB_TOKEN }} publish
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: 1d8690130
        path: build/libs
